name: bit-cacher
version: 0.1
summary: Bit-cacher will store names
description: |
  Only useful for very specific purposes
confinement: strict

apps:
  bit-cacher:
    command: bin/bit-cacher
    plugs: [network-bind]

parts:
  bit-cacher-bin:
    plugin: go
    source: ./


